all:	
	pdflatex presentacion-tesis.tex
	pdflatex presentacion-tesis.tex
	evince presentacion-tesis.pdf
	make clean
	
clean:	
	rm -f *.log
	rm -f *.aux
	rm -f *.dvi
	rm -f *.nav
	rm -f *.out
	rm -f *.snm
	rm -f *.toc
	rm -f *.vrb
